# Thanks BrainlessSociety!
################################################################################
# Base stage
################################################################################
ARG RUST_VERSION
ARG DEBIAN_VERSION
FROM rust:${RUST_VERSION:-latest} AS base

ARG SERVICE_NAME

################################################################################
# Chef stage
################################################################################
FROM base AS chef

# Install cargo-chef. Used to cache dependencies
RUN cargo install cargo-chef


################################################################################
# Planner stage
################################################################################
FROM chef AS planner

WORKDIR /app

COPY . .

# delete top level Cargo.toml
RUN rm -f Cargo.toml && rm -f Cargo.lock

WORKDIR /app/${SERVICE_NAME}

RUN cargo chef prepare --recipe-path recipe.json


################################################################################
# Build stage
################################################################################
FROM chef AS builder


WORKDIR /app/${SERVICE_NAME}

COPY --from=planner /app/${SERVICE_NAME}/recipe.json recipe.json

COPY task_worker /app/task_worker
COPY gt_ffmpeg /app/gt_ffmpeg

# Build dependencies. This is the caching Docker layer
RUN cargo chef cook --release --recipe-path recipe.json

WORKDIR /app

COPY . .

# delete top level Cargo.toml
RUN rm -f Cargo.toml && rm -f Cargo.lock

WORKDIR /app/${SERVICE_NAME}

# Run tests (If enabled)
ARG RUN_TESTS=false
RUN if [ "$RUN_TESTS" = "true" ]; then cargo test --release; fi

# Build application
RUN cargo build --release


################################################################################
# Final stage
################################################################################
FROM debian:${DEBIAN_VERSION:-latest} AS runtime

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  libssl-dev \
  pkg-config \
  ffmpeg \
  python3 \
  python3-pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install openai whisper
RUN pip3 install --break-system-packages openai-whisper

# Create a non-root user to run the app
ARG USER=user
ARG UID=10001


RUN adduser \
  --disabled-password \
  --gecos "" \
  --home "/nonexistent" \
  --shell "/sbin/nologin" \
  --no-create-home \
  --uid "${UID}" \
  "${USER}"

RUN mkdir /model
RUN chown ${USER}:${USER} /model

USER ${USER}:${USER}

ARG SERVICE_NAME

# check that SERVICE_NAME is set
RUN test -n "${SERVICE_NAME}"

WORKDIR /app/${SERVICE_NAME}

COPY --from=builder --chown=${USER}:${USER} /app/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/service_api

ENV CARGO_MANIFEST_DIR=/app/${SERVICE_NAME}

EXPOSE 3000

ENTRYPOINT [ "service_api" ]