name: video_processing_project

x-backend-variables: &backend-variables
  HOST: 0.0.0.0
  PORT: 3000
  RUST_LOG: trace
  RUST_BACKTRACE: 1
  CORS_ALLOWED_ORIGINS: http://localhost:8080
  TASK_API_URL: http://api:3000/tasks
  TASK_API_EXTERNAL_URL: http://localhost:8080/api/records/tasks

services:
  proxy:
    image: nginx:1.25.1-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      # nginx:1.25.1-alpine does not have curl installed
      test: ["CMD", "wget", "-q", "--spider", "--tries=1", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - frontend
      - api

  # run our frontend in dev mode with hot module reloading for vite
  frontend:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # From end user perspective
      VITE_API_URL: http://localhost:8080/api
      VITE_YOUTUBE_AUTH_URI: ${YOUTUBE_AUTH_URI}
    healthcheck:
      # node:18-alpine does not have curl installed
      test: ["CMD", "wget", "-q", "--spider", "--tries=1", "http://localhost:3000"]
      interval: 60s
      timeout: 30s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.rust
      args:
        - SERVICE_NAME=api
        - DEBIAN_VERSION=bookworm-slim
        - RUST_VERSION=1.78
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/video_processing_project
      VIDEO_STORAGE_PATH: /obs
      NOISE: 0.004
      DURATION: 2.0
      THIS_API_BASE_URL: http://api:3000
      RENDERED_EPISODE_STORAGE_PATH: /renders
      MODEL_PATH: /model
      REDIS_URL: redis://redis:6379
      QUEUE_NAME: task_queue
      TWITCH_USER_ID: ${TWITCH_USER_ID}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET_PATH: /twitch_client_secret
      TWITCH_REDIRECT_URL: http://localhost:8080/twitch/callback
      YOUTUBE_AUTH_URI: http://localhost:8080/youtubeLogin
      YOUTUBE_TOKEN_URI: ${YOUTUBE_TOKEN_URI}
      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
      YOUTUBE_CLIENT_SECRET_PATH: /youtube_client_secret
      YOUTUBE_REDIRECT_URL: http://localhost:8080/youtube/callback
      OPENAI_KEY_PATH: /openai_key
      OPENAI_MODEL: gpt-4o
      <<: *backend-variables
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - obs:/obs
      - renders:/renders
      - ./youtube_key.txt:/youtube_client_secret
      - ./twitch_key.txt:/twitch_client_secret
      - ./openai_key.txt:/openai_key
      - model:/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  task_worker:
    build:
      context: .
      dockerfile: Dockerfile.rust
      args:
        - SERVICE_NAME=task_worker
        - DEBIAN_VERSION=bookworm-slim
        - RUST_VERSION=1.78
    restart: always
    depends_on:
      - redis
    environment:
      <<: *backend-variables
      REDIS_URL: redis://redis:6379
      QUEUE_NAME: task_queue
    deploy:
      mode: replicated
      replicas: 3

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: video_processing_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  obs:
  renders:
  audio:
  model:
  postgres_data:
  redis_data:
