[package]
name = "summarize_transcription"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.5"
lambda_runtime = "0.13.0"
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }

[lints]
workspace = true
