
[package]
name = "task_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = { version = "0.15.7" }
tokio = { version = "1.0", features = ["full"] }
tracing = { version = "0.1.40" }
redis = { version = "0.24.0", features = ["aio", "json", "tokio-comp"] }
reqwest = { version = "0.11.22", features = ["json", "rustls-tls"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
