[package]
name = "crud_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_api_lib = { path = "../common_api_lib" }
axum = "0.6.20"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tracing = { version = "0.1.40" }
diesel = { version = "2", features = ["chrono", "uuid"] }
diesel-async = { version = "0.4.1", features = ["postgres", "bb8"] }
chrono = "0.4.31"
uuid = "1.6.1"
