---
openapi: 3.1.1
info:
  title: Glowing Telegram API
  version: "2.0"
components:
  schemas:
    Series:
      $ref: "./schemas/Series.schema"
    Stream:
      $ref: "./schemas/Stream.schema"
    Episode:
      $ref: "./schemas/Episode.schema"
    Profile:
      $ref: "./schemas/Profile.schema"
    StreamIngestionRequest:
      $ref: "./schemas/StreamIngestionRequest.schema"
    VideoClip:
      $ref: "./schemas/VideoClip.schema"
    IdOnly:
      $ref: "./schemas/IdOnly.schema"
    Record:
      type: object
      oneOf:
        - $ref: "#/components/schemas/Series"
        - $ref: "#/components/schemas/Stream"
        - $ref: "#/components/schemas/Episode"
        - $ref: "#/components/schemas/Profile"
        - $ref: "#/components/schemas/VideoClip"
    TwitchAuthRequest:
      $ref: "./schemas/TwitchAuthRequest.schema"
    AuthorizationUrlResponse:
      $ref: "./schemas/AuthorizationUrlResponse.schema"
    TwitchCallbackRequest:
      $ref: "./schemas/TwitchCallbackRequest.schema"
    AccessTokenResponse:
      $ref: "./schemas/AccessTokenResponse.schema"
    SimpleChatMessage:
      $ref: "./schemas/SimpleChatMessage.schema"

  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
paths:
  /ai/chat:
    post:
      summary: Chat with AI
      tags:
        - chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    $ref: "#/components/schemas/SimpleChatMessage"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: "#/components/schemas/SimpleChatMessage"
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
  /records/{resource}:
    get:
      summary: List records
      tags:
        - list
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: filter
          in: query
          schema:
            type: string
            format: json
            content:
              application/json:
                schema:
                  type: object
        - name: cursor
          in: query
          schema:
            type: string
        - name: perPage
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Record"
                  cursor:
                    type: string
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
    post:
      summary: Create a record
      tags:
        - create
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Record"
                - $ref: "#/components/schemad/StreamIngestionRequest"
      responses:
        "201":
          description: Record created
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Record"
                  - $ref: "#/components/schemas/IdOnly"
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
  /records/{resource}/{record_id}:
    get:
      summary: Get a record
      tags:
        - get
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: record_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Record"
        "400":
          $ref: "#/components/responses/Error"
        "404":
          description: Record not found
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
    put:
      summary: Update a record
      tags:
        - update
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: record_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Record"
      responses:
        "200":
          description: Record updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
    delete:
      summary: Delete a record
      tags:
        - delete
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: record_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Record deleted
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
  /records/{resource}/{related_field}/{id}:
    get:
      summary: Get related records
      tags:
        - get
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: related_field
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Record"
                  cursor:
                    type: string
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
  /records/{resource}/many:
    get:
      summary: Get many records
      tags:
        - get
      parameters:
        - name: resource
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Record"
        "400":
          $ref: "#/components/responses/Error"
        "500":
          $ref: "#/components/responses/Error"
  /auth/twitch/url:
    post:
      summary: Obtain Twitch authorization URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwitchAuthRequest"
      responses:
        "200":
          description: Authorization URL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorizationUrlResponse"
  /auth/twitch/callback:
    get:
      summary: Handle Twitch callback
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Redirect to client
  /auth/twitch/token:
    get:
      summary: Obtain Twitch access token
      responses:
        "200":
          description: Access token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
