name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        if: github.event_name == 'pull_request'
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ./docker-bake.override.hcl
          targets: all
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Build and push Docker images
        if: github.event_name != 'pull_request'
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ./docker-bake.override.hcl
          targets: all
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max