name: Build and Push Docker Images

on:
  release:
    types: [published]

env:
  REGISTRY: 159222827421.dkr.ecr.us-west-2.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::159222827421:role/RepoStack-DockerGithubActionRole
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ./docker-bake.override.hcl
          targets: all
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          IMAGE_TAG: ${{ github.ref_name }}