name: "Publish TypeScript types to npm"

on:
  release: 
    types: ["published"]

jobs:
  publish_ts_types:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write

    defaults:
      run:
        working-directory: types

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci
        
      - name: Update package.json version to match release tag
        run: |
          # Extract version from release tag (remove 'v' prefix if present)
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          VERSION=${RELEASE_VERSION#v}
          
          # Validate version format (strict semver check)
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?(\+[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$ ]]; then
            echo "Error: Invalid version format '$VERSION'. Must follow semver format (x.y.z with optional pre-release and build metadata)"
            exit 1
          fi
          
          echo "Updating package.json version from release tag: $RELEASE_VERSION -> $VERSION"
          
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Update package.json version only if different
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            npm version "$VERSION" --no-git-tag-version
          else
            echo "Version is already $VERSION, no update needed"
          fi
          
          # Verify the update
          UPDATED_VERSION=$(node -p "require('./package.json').version")
          if [ "$UPDATED_VERSION" != "$VERSION" ]; then
            echo "Error: Version update failed. Expected: $VERSION, Got: $UPDATED_VERSION"
            exit 1
          fi
          
          echo "Successfully updated package.json version to $VERSION"

      - name: Generate TypeScript types
        run: ./import.sh

      - name: Check if types have changed
        id: check_changes
        run: |
          # Get the latest published version from npm
          LATEST_PUBLISHED=$(npm view @saebyn/glowing-telegram-types version 2>/dev/null || echo "")
          
          if [ -z "$LATEST_PUBLISHED" ]; then
            echo "No published version found, proceeding with publish"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Checking for changes against latest published version: $LATEST_PUBLISHED"
          
          # Download the currently published types file from npm
          # Create a unique temp directory for comparison
          PUBLISHED_TYPES_DIR=$(mktemp -d)
          
          # Try to download the published package
          PACKED_FILE=$(npm pack @saebyn/glowing-telegram-types@$LATEST_PUBLISHED --pack-destination "$PUBLISHED_TYPES_DIR" 2>/dev/null)
          if [ $? -eq 0 ] && [ -n "$PACKED_FILE" ]; then
            # Extract the package
            cd "$PUBLISHED_TYPES_DIR"
            tar -xzf "$PACKED_FILE"
            
            # Compare the types files
            if diff -q package/src/types.ts "$GITHUB_WORKSPACE/types/src/types.ts" > /dev/null 2>&1; then
              echo "No changes detected in types.ts file compared to published version $LATEST_PUBLISHED"
              echo "has_changes=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected in types.ts file compared to published version $LATEST_PUBLISHED"
              echo "has_changes=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "Could not download published version $LATEST_PUBLISHED, proceeding with publish"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
          
          # Clean up temporary directory
          rm -rf "$PUBLISHED_TYPES_DIR"

      - name: Publish to npm
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Skip publishing - no changes
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "Skipping npm publish - no changes detected in TypeScript types since last published version"