name: Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

env:
  PYTHON_VERSION: "3.11"

jobs:
  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov boto3 pyjwt cryptography psycopg2-binary
          # Install dependencies for websocket authorizer if Pipfile exists
          if [ -f "cdk/lib/websocketAuthorizer/Pipfile" ]; then
            pip install pipenv
            cd cdk/lib/websocketAuthorizer && pipenv install --dev --system
          fi
          
      - name: Run Python tests
        run: |
          python -m pytest